[package]
name = "muse-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
# GTK and UI
gtk4 = { version = "0.9", features = ["v4_14"] }
gtk4-layer-shell = "0.4"
glib = "0.20"
gio = "0.20"
gdk4 = { version = "0.9", features = ["v4_14"] }
pango = "0.20"

# Async and concurrency
tokio = { version = "1.40", features = ["full"] }
async-channel = "2.3"
futures = "0.3"

# System integration
zbus = { version = "4.0", features = ["tokio"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.11"
once_cell = "1.19"
chrono = "0.4"

# System monitoring
sysinfo = "0.31"
procfs = "0.16"

# Network management (placeholder - will implement later)
# nm-rs = { version = "0.1", optional = true }

# Audio (placeholder - will implement later)  
# pipewire = { version = "0.8", optional = true }
# wireplumber = { version = "0.2", optional = true }

[build-dependencies]
glib-build-tools = "0.20"

[features]
default = []
# networkmanager = ["nm-rs"]
# audio = ["pipewire", "wireplumber"]