[package]
name = "muse-shell"
version = "0.1.0"
edition = "2021"
description = "muni's desktop shell - A modern desktop shell built with Rust and GTK4"

[dependencies]
# GTK and UI
gtk4 = { version = "0.9", features = ["v4_14"] }
gtk4-layer-shell = "0.5"
glib = "0.20"
gio = "0.20"
gdk4 = { version = "0.9", features = ["v4_14"] }
pango = "0.20"

# Relm4 - Modern GTK4 framework
relm4 = { version = "0.9", features = ["macros"] }
relm4-components = "0.9"

# Async and concurrency
tokio = { version = "1", features = ["full"] }
async-channel = "2.3"

# System integration
zbus = { version = "5", features = ["tokio"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Utilities
anyhow = "1"
thiserror = "2"
log = "0.4"
env_logger = "0.11"
chrono = "0.4"

# System monitoring
sysinfo = "0.37"
procfs = "0.17"
futures-lite = { version = "2", default-features = false }

# Network management (placeholder - will implement later)
# nm-rs = { version = "0.1", optional = true }

# Audio (placeholder - will implement later)
# pipewire = { version = "0.8", optional = true }
# wireplumber = { version = "0.2", optional = true }

[build-dependencies]
glib-build-tools = "0.21"

[features]
default = []
# networkmanager = ["nm-rs"]
# audio = ["pipewire", "wireplumber"]